---
output:
  pdf_document: 
    number_sections: true
    fig_caption: true
    keep_tex: true
    latex_engine: xelatex
    extra_dependencies: ["float"]
  html_document: default
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Lade notwendige Bibliothek
library(readr)
library(knitr)

# Lade die CSV-Datei in ein DataFrame
file_path <- "../1_Datenset/ursprüngliche/netflix_titles.csv"
movies_df <- read_csv(file_path)

# Erstelle ein neues DataFrame für die Tabelle
spalten <- colnames(movies_df)
beschreibung <- c(
    "Einzigartige ID der Show", 
    "Film oder Serie", 
    "Titel der Show", 
    "Regisseur", 
    "Besetzung",
    "Produktionsland",
    "Hinzufügedatum",
    "Veröffentlichungsjahr",
    "Altersfreigabe",
    "Laufzeit in Minuten oder Staffeln",
    "Genres",
    "Kurzbeschreibung"
)
relevanz <- c(
    "nein",
    "ja",
    "ja",
    "ja",
    "ja",
    "ja",
    "nein",
    "nein",
    "ja",
    "ja",
    "ja",
    "ja"
)

# Kombiniere die Beschreibungen und Relevanzen in ein neues DataFrame
tabelle_df <- data.frame(Spalten =spalten, Beschreibung = beschreibung, Relevanz = relevanz)

# Zeige die Tabelle an
kable(
  tabelle_df,
  align = c("r", "l", "c"),
  col.names = c("Spalten", "Beschreibung", "Relevant?"),
  caption = "Tabelle der Beschreibungen und Relevanzen"
)
```
```{r}
# Lade notwendige Bibliothek
library(readr)
library(knitr)

# Lade die CSV-Datei in ein DataFrame
file_path <- "../1_Datenset/erstellte/fertig/fertig.csv"
movies_df <- read_csv(file_path)

# Erstelle ein neues DataFrame für die Tabelle
spalten <- colnames(movies_df)
beschreibung <- c(
    "Einzigartige ID der Show", 
    "Film oder Serie", 
    "Titel der Show", 
    "Regisseur", 
    "Besetzung",
    "Produktionsland",
    "Veröffentlichungsjahr",
    "Altersfreigabe",
    "Laufzeit in Minuten oder Staffeln",
    "Genres",
    "Kurzbeschreibung",
    "Netflix oder Disney+"
)
relevanz <- c(
    "nein",
    "ja",
    "ja",
    "ja",
    "ja",
    "ja",
    "nein",
    "ja",
    "ja",
    "ja",
    "ja",
    "ja"
)

# Kombiniere die Beschreibungen und Relevanzen in ein neues DataFrame
tabelle_df <- data.frame(Spalten =spalten, Beschreibung = beschreibung, Relevanz = relevanz)

# Zeige die Tabelle an
kable(
  tabelle_df,
  align = c("r", "l", "c"),
  col.names = c("Spalten", "Beschreibung", "Relevant?"),
  caption = "Tabelle der Beschreibungen und Relevanzen"
)
```