---
output:
  pdf_document: 
    number_sections: true
    fig_caption: true
    keep_tex: true
    latex_engine: xelatex
    extra_dependencies: ["float"]
  html_document: default
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Lade notwendige Bibliothek
library(readr)
library(knitr)
library(dplyr)
library(kableExtra)

# Lade die CSV-Datei in ein DataFrame
file_path <- "../1_Datenset/ursprüngliche/netflix_titles.csv"
movies_df <- read_csv(file_path)

# Erstelle ein neues DataFrame für die Tabelle
spalten <- colnames(movies_df)
datentypen <- c(
  "Absolut",
  "Nominal",
  "Nominal",
  "Nominal",
  "Nominal",
  "Nominal",
  "Ordinal",
  "Ordinal",
  "Ordinal",
  "Interval",
  "Nominal",
  "Nominal"
)
beschreibung <- c(
    "Einzigartige ID der Show", 
    "Film oder Serie", 
    "Titel der Show", 
    "Regisseur", 
    "Besetzung",
    "Produktionsland",
    "Hinzufügedatum",
    "Veröffentlichungsjahr",
    "Altersfreigabe",
    "Laufzeit in Minuten oder Staffeln",
    "Genres",
    "Kurzbeschreibung"
)
relevanz <- c(
    "nein",
    "ja",
    "ja",
    "ja",
    "ja",
    "ja",
    "nein",
    "nein",
    "ja",
    "ja",
    "ja",
    "ja"
)

# Kombiniere die Beschreibungen und Relevanzen in ein neues DataFrame
tabelle_df <- data.frame(Spalten =spalten, Datentypen=datentypen,  Beschreibung = beschreibung, Relevanz = relevanz)

# Zeige die Tabelle an
kable(
  tabelle_df,
  align = c("r", "c", "l", "c"),
  col.names = c("Spalten", "Datentypen", "Beschreibung", "Relevant?"),
  caption = "Tabelle der Beschreibungen und Relevanzen"
)
```
```{r}

# Lade die CSV-Datei in ein DataFrame
file_path <- "../1_Datenset/erstellte/fertig/fertig.csv"
movies_df <- read_csv(file_path)

# Erstelle ein neues DataFrame für die Tabelle
spalten <- colnames(movies_df)
beschreibung <- c(
    "Einzigartige ID der Show", 
    "Film oder Serie", 
    "Titel der Show", 
    "Regisseur", 
    "Besetzung",
    "Produktionsland",
    "Altersfreigabe",
    "Laufzeit in Minuten oder Staffeln",
    "Genres",
    "Kurzbeschreibung",
    "Netflix oder Disney+"
)
relevanz <- c(
    "nein",
    "ja",
    "ja",
    "ja",
    "ja",
    "ja",
    "ja",
    "ja",
    "ja",
    "ja",
    "ja"
)

# Kombiniere die Beschreibungen und Relevanzen in ein neues DataFrame
tabelle_df <- data.frame(Spalten =spalten, Beschreibung = beschreibung, Relevanz = relevanz)

# Zeige die Tabelle an
kable(
  tabelle_df,
  align = c("r", "l", "c"),
  col.names = c("Spalten", "Beschreibung", "Relevant?"),
  caption = "Tabelle der Beschreibungen und Relevanzen"
)
```

```{r}

# Erstelle die Daten für die Tabelle
bewertung <- c("TV-Y", "TV-Y7", "TV-Y7 FV", "TV-G", "TV-PG", "TV-14", "TV-MA", "G", "PG", "PG-13", "R", "NC-17", "NR", "UR")
altersfreigabe <- c(
  "Für alle Kinder", "Ab 7 Jahren", "Ab 7 Jahren mit Fantasy-Gewalt", "Für alle Altersgruppen", 
  "Ab 10 Jahren mit Elternaufsicht", "Ab 14 Jahren", "Ab 17 Jahren", "Für alle Altersgruppen", 
  "Ab 10 Jahren mit Elternaufsicht", "Ab 13 Jahren", "Ab 17 Jahren", "Ab 18 Jahren", "Keine Bewertung", "Keine Bewertung"
)

# Passende Beschreibungen in der neuen Reihenfolge
beschreibung <- c(
  "Für alle Kinder im Alter von 2 bis 6 Jahren geeignet",
  "Enthält milde Fantasie oder komödiantische Gewalt.",
  "Enthält Fantasy-Gewalt, die kämpferischer ist als TVY7-Programme.",
  "Für Zuschauer jeden Alters geeignet. Keine bedenklichen Inhalte.",
  "Vorgesehen für jüngere Kinder in Begleitung eines Erwachsenen.",
  "Für Jugendliche ab 14 Jahren in begleitung eines Erwachsenen. Kann intensivere Themen oder Sprache enthalten.",
  "Für Erwachsene. Kann starke Sprache, Gewalt oder sexuelle Inhalte enthalten.",
  "Für alle Altersgruppen geeignet. Keine bedenklichen Inhalte.",
  "Einige Inhalte könnten für jüngere Kinder ungeeignet sein. Elternaufsicht empfohlen.",
  "Für Jugendliche ab 13 Jahren. Kann mildere Gewalt oder Sprache enthalten. Eltern werden gewarnt.",
  "Für Erwachsene. Kann Gewalt, Drogenkonsum oder starke Sprache enthalten.",
  "Nur für Erwachsene. Kann extreme Gewalt oder sexuelle Inhalte enthalten.",
  "Der Inhalt wurde nicht bewertet. Zuschauer sollten selbst entscheiden.",
  "Der Inhalt wurde nicht bewertet oder handelt sich um eine spezielle Version. Vorsicht geboten."
)


# Erstelle das DataFrame für die Tabelle
tabelle_df <- data.frame(
  Bewertung = bewertung,
  Altersfreigabe = altersfreigabe,
  Beschreibung = beschreibung
)

kable(
  tabelle_df,
  align = c("l", "c", "l"),
  col.names = c("Bewertung", "Altersfreigabe", "Beschreibung"),
  caption = "Altersfreigaben und ihre Bedeutung",
  escape = FALSE
) %>%
  kable_styling(full_width = FALSE) %>%
  column_spec(1, width = "8em")  # Passen Sie die Breite nach Bedarf an

```